name: CI Pipeline to staging/production environment
on:
  pull_request:
    branches:
      - main
jobs: 
  test:
    runs-on: ubuntu-latest
    name: Setup, test, and build project
    env:
      PORT: 5001
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Test application
        run:  test

      - name: Build application
        run: |
          echo "Run command to build
          
