name: CI Pipeline to staging/production environment
on:
  pull_request:
    branches:
      - main
jobs: 
  test:
    runs-on: ubuntu-latest
    name: Setup, test, and build project
    env:
      PORT: 5001
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # specify your Node.js version here

      - name: Install dependencies
        run: npm install

      - name: Test application
        run: npm test  # Replace with your test command if different

      - name: Build application
        run: npm run build  # Only if you have a build script
